export const PERMISSIONS = {
  FREEZE_CUSTOMER: ["FREEZE_CUSTOMER_PLATFORM", "FREEZE_CUSTOMER_ORGANISATION"],
  UNFREEZE_CUSTOMER: [
    "FREEZE_CUSTOMER_PLATFORM",
    "FREEZE_CUSTOMER_ORGANISATION",
  ],
  SET_CUSTOMER_TIER: "UPDATE_CUSTOMER_PLATFORM",
  LEDGER_ADJUSTMENT: "LEDGER_ADJUSTMENT_PLATFORM",
  MANAGE_WALLETS_PLATFORM: "MANAGE_WALLETS_PLATFORM",
} as const;
