import type { ApprovalRequest } from "@/types/approvalQueue";

export const MOCK_APPROVAL_QUEUE: ApprovalRequest[] = [
  {
    id: "aq-001",
    type: "transfers",
    title: "Transfer to Vendor – Zenith Supplies",
    description: "Monthly supply payment to Zenith Supplies Ltd for office materials",
    amount: 8_500_000,
    currency: "NGN",
    initiator: { id: "u-010", name: "Aisha Bello", role: "initiator" },
    currentStep: 1,
    totalSteps: 2,
    status: "pending",
    priority: "normal",
    createdAt: "2026-03-28T09:15:00Z",
    dueBy: "2026-04-01T09:15:00Z",
    approvalHistory: [],
  },
  {
    id: "aq-002",
    type: "transfers",
    title: "International Wire – USD Payment",
    description: "Payment for imported server equipment from CloudTech Inc, Delaware",
    amount: 45_000_000,
    currency: "NGN",
    initiator: { id: "u-011", name: "Chidi Okwuosa", role: "initiator" },
    currentStep: 1,
    totalSteps: 3,
    status: "pending",
    priority: "high",
    createdAt: "2026-03-29T14:30:00Z",
    dueBy: "2026-04-02T14:30:00Z",
    approvalHistory: [],
  },
  {
    id: "aq-003",
    type: "bulk_payments",
    title: "Vendor Batch – March Payments",
    description: "Batch payment to 12 vendors for March deliveries",
    amount: 3_200_000,
    currency: "NGN",
    initiator: { id: "u-012", name: "Ngozi Adeyemi", role: "initiator" },
    currentStep: 2,
    totalSteps: 2,
    status: "pending",
    priority: "normal",
    createdAt: "2026-03-27T11:00:00Z",
    dueBy: "2026-03-31T11:00:00Z",
    approvalHistory: [
      {
        id: "ah-001",
        actorName: "Emeka Obi",
        actorRole: "authorizer",
        action: "approved",
        comment: "Verified against POs. All amounts match.",
        timestamp: "2026-03-28T10:00:00Z",
        stepNumber: 1,
      },
    ],
  },
  {
    id: "aq-004",
    type: "payroll",
    title: "March 2026 Payroll Run",
    description: "Monthly payroll disbursement for 85 employees",
    amount: 28_000_000,
    currency: "NGN",
    initiator: { id: "u-013", name: "Fatima Bello", role: "initiator" },
    currentStep: 1,
    totalSteps: 2,
    status: "escalated",
    priority: "critical",
    createdAt: "2026-03-25T08:00:00Z",
    dueBy: "2026-03-28T08:00:00Z",
    approvalHistory: [
      {
        id: "ah-002",
        actorName: "System",
        actorRole: "owner",
        action: "escalated",
        comment: "Auto-escalated: no action within 24 hours",
        timestamp: "2026-03-26T08:00:00Z",
        stepNumber: 1,
      },
    ],
  },
  {
    id: "aq-005",
    type: "user_management",
    title: "New User Invitation – Tunde Bakare",
    description: "Invite Tunde Bakare as Initiator role for Lagos Digital Hub",
    amount: null,
    currency: "NGN",
    initiator: { id: "u-010", name: "Aisha Bello", role: "initiator" },
    currentStep: 1,
    totalSteps: 1,
    status: "pending",
    priority: "normal",
    createdAt: "2026-03-30T16:00:00Z",
    dueBy: null,
    approvalHistory: [],
  },
  // History items (already resolved)
  {
    id: "aq-006",
    type: "transfers",
    title: "Transfer to GTBank – Rent Payment",
    description: "Q1 2026 office rent payment to Mainland Properties Ltd",
    amount: 4_500_000,
    currency: "NGN",
    initiator: { id: "u-011", name: "Chidi Okwuosa", role: "initiator" },
    currentStep: 1,
    totalSteps: 1,
    status: "approved",
    priority: "normal",
    createdAt: "2026-03-15T10:00:00Z",
    dueBy: null,
    approvalHistory: [
      {
        id: "ah-003",
        actorName: "Adewale Ogundimu",
        actorRole: "authorizer",
        action: "approved",
        comment: "Rent confirmed with landlord. Proceed.",
        timestamp: "2026-03-15T14:30:00Z",
        stepNumber: 1,
      },
    ],
  },
  {
    id: "aq-007",
    type: "bulk_payments",
    title: "February Vendor Batch",
    description: "Batch payment to 8 vendors for February",
    amount: 1_800_000,
    currency: "NGN",
    initiator: { id: "u-012", name: "Ngozi Adeyemi", role: "initiator" },
    currentStep: 1,
    totalSteps: 1,
    status: "rejected",
    priority: "normal",
    createdAt: "2026-03-01T09:00:00Z",
    dueBy: null,
    approvalHistory: [
      {
        id: "ah-004",
        actorName: "Emeka Obi",
        actorRole: "authorizer",
        action: "rejected",
        comment: "Two invoices are duplicated. Please correct and resubmit.",
        timestamp: "2026-03-02T11:00:00Z",
        stepNumber: 1,
      },
    ],
  },
  {
    id: "aq-008",
    type: "transfers",
    title: "Transfer to Access Bank – Equipment",
    description: "Payment for networking equipment from NetGear Nigeria",
    amount: 12_500_000,
    currency: "NGN",
    initiator: { id: "u-010", name: "Aisha Bello", role: "initiator" },
    currentStep: 3,
    totalSteps: 3,
    status: "approved",
    priority: "high",
    createdAt: "2026-03-10T08:00:00Z",
    dueBy: null,
    approvalHistory: [
      {
        id: "ah-005",
        actorName: "Emeka Obi",
        actorRole: "authorizer",
        action: "approved",
        comment: "PO verified.",
        timestamp: "2026-03-10T12:00:00Z",
        stepNumber: 1,
      },
      {
        id: "ah-006",
        actorName: "Adewale Ogundimu",
        actorRole: "authorizer",
        action: "approved",
        comment: "Budget confirmed.",
        timestamp: "2026-03-11T09:00:00Z",
        stepNumber: 2,
      },
      {
        id: "ah-007",
        actorName: "Ibrahim Musa",
        actorRole: "owner",
        action: "approved",
        comment: "Final approval granted.",
        timestamp: "2026-03-11T15:00:00Z",
        stepNumber: 3,
      },
    ],
  },
];
