import type {
  Application,
  ApplicationSummary,
  DashboardSummary,
  UserProfile,
  Director,
  KYCDocument,
  FeedbackItem,
  TimelineEvent,
} from "@/types/onboarding";

// ── Mock User ──────────────────────────────────────────────

export const mockUser: UserProfile = {
  id: "00000000-0000-4000-a000-000000000001",
  email: "applicant@technovasolutions.com",
  full_name: "Adewale Ogundimu",
  phone_number: "+2348012345678",
  force_password_change: false,
  onboarding_completed: true,
  registration_path: "self_registration",
  created_at: "2025-12-01T09:00:00Z",
  role: "owner",
};

// ── Helper dates ───────────────────────────────────────────

const d = (iso: string) => iso;

// ── Directors ──────────────────────────────────────────────

const dangoteDirectors: Director[] = [
  {
    id: "dir-d1",
    full_name: "Aliko Dangote",
    role: "director_and_signatory",
    date_of_birth: "1957-04-10",
    nationality: "Nigeria",
    bvn: "12345678901",
    phone_number: "+2348001111111",
    email: "aliko@dangote.com",
    residential_address: "1 Alfred Rewane Road, Ikoyi, Lagos",
    id_type: "international_passport",
    id_number: "A12345678",
    id_expiry_date: "2028-04-10",
    verification_status: "verified",
    verification_sent_at: d("2025-11-05T10:00:00Z"),
    verification_completed_at: d("2025-11-05T12:30:00Z"),
    id_document_uploaded: true,
    passport_photo_uploaded: true,
    signature_uploaded: true,
    created_at: d("2025-11-01T09:00:00Z"),
  },
  {
    id: "dir-d2",
    full_name: "Halima Dangote",
    role: "director",
    date_of_birth: "1970-08-22",
    nationality: "Nigeria",
    bvn: "12345678902",
    phone_number: "+2348001111112",
    email: "halima@dangote.com",
    residential_address: "5 Bourdillon Road, Ikoyi, Lagos",
    id_type: "national_id_nin",
    id_number: "NIN987654321",
    id_expiry_date: "2029-01-01",
    verification_status: "verified",
    verification_sent_at: d("2025-11-05T10:00:00Z"),
    verification_completed_at: d("2025-11-06T08:00:00Z"),
    id_document_uploaded: true,
    passport_photo_uploaded: true,
    signature_uploaded: true,
    created_at: d("2025-11-01T09:00:00Z"),
  },
];

const techNovaDirectors: Director[] = [
  {
    id: "dir-t1",
    full_name: "Chidi Okwuosa",
    role: "director_and_signatory",
    date_of_birth: "1985-03-15",
    nationality: "Nigeria",
    bvn: "22345678901",
    phone_number: "+2348022222221",
    email: "chidi@technova.ng",
    residential_address: "12 Admiralty Way, Lekki Phase 1, Lagos",
    id_type: "drivers_license",
    id_number: "DL-LAG-12345",
    id_expiry_date: "2027-06-30",
    verification_status: "verified",
    verification_sent_at: d("2025-12-10T14:00:00Z"),
    verification_completed_at: d("2025-12-10T16:00:00Z"),
    id_document_uploaded: true,
    passport_photo_uploaded: true,
    signature_uploaded: true,
    created_at: d("2025-12-05T09:00:00Z"),
  },
  {
    id: "dir-t2",
    full_name: "Ngozi Adeyemi",
    role: "signatory",
    date_of_birth: "1990-07-20",
    nationality: "Nigeria",
    bvn: "22345678902",
    phone_number: "+2348022222222",
    email: "ngozi@technova.ng",
    residential_address: "8 Victoria Island, Lagos",
    id_type: "international_passport",
    id_number: "B98765432",
    id_expiry_date: "2028-12-31",
    verification_status: "verified",
    verification_sent_at: d("2025-12-10T14:00:00Z"),
    verification_completed_at: d("2025-12-11T09:00:00Z"),
    id_document_uploaded: true,
    passport_photo_uploaded: true,
    signature_uploaded: true,
    created_at: d("2025-12-05T09:00:00Z"),
  },
  {
    id: "dir-t3",
    full_name: "Emeka Obi",
    role: "director",
    date_of_birth: "1982-11-02",
    nationality: "Nigeria",
    bvn: "22345678903",
    phone_number: "+2348022222223",
    email: "emeka@technova.ng",
    residential_address: "3 Allen Avenue, Ikeja, Lagos",
    id_type: "voters_card",
    id_number: "VC-1234567890",
    id_expiry_date: "2030-01-01",
    verification_status: "email_sent",
    verification_sent_at: d("2025-12-15T10:00:00Z"),
    verification_completed_at: null,
    id_document_uploaded: true,
    passport_photo_uploaded: true,
    signature_uploaded: false,
    created_at: d("2025-12-05T09:00:00Z"),
  },
];

const petroChemDirectors: Director[] = [
  {
    id: "dir-p1",
    full_name: "Ibrahim Musa",
    role: "director_and_signatory",
    date_of_birth: "1975-05-18",
    nationality: "Nigeria",
    bvn: "33345678901",
    phone_number: "+2348033333331",
    email: "ibrahim@petrochem.ng",
    residential_address: "22 Adeola Odeku, VI, Lagos",
    id_type: "international_passport",
    id_number: "C11223344",
    id_expiry_date: "2027-09-15",
    verification_status: "verified",
    verification_sent_at: d("2026-01-10T08:00:00Z"),
    verification_completed_at: d("2026-01-10T11:00:00Z"),
    id_document_uploaded: true,
    passport_photo_uploaded: true,
    signature_uploaded: true,
    created_at: d("2026-01-05T09:00:00Z"),
  },
  {
    id: "dir-p2",
    full_name: "Fatima Bello",
    role: "signatory",
    date_of_birth: "1988-02-28",
    nationality: "Nigeria",
    bvn: "33345678902",
    phone_number: "+2348033333332",
    email: "fatima@petrochem.ng",
    residential_address: "7 Ozumba Mbadiwe, VI, Lagos",
    id_type: "national_id_nin",
    id_number: "NIN1122334455",
    id_expiry_date: "2029-06-30",
    verification_status: "email_sent",
    verification_sent_at: d("2026-01-12T14:00:00Z"),
    verification_completed_at: null,
    id_document_uploaded: true,
    passport_photo_uploaded: true,
    signature_uploaded: true,
    created_at: d("2026-01-05T09:00:00Z"),
  },
];

// ── Documents helper ───────────────────────────────────────

function makeDocList(uploaded: boolean, statuses?: Partial<Record<string, string>>): KYCDocument[] {
  const docDefs: { type: string; label: string; required: boolean; maxMb: number; types: string[] }[] = [
    { type: "cac_certificate", label: "CAC Certificate", required: true, maxMb: 5, types: ["pdf", "jpg", "png"] },
    { type: "memart", label: "MEMART", required: true, maxMb: 10, types: ["pdf"] },
    { type: "board_resolution", label: "Board Resolution", required: true, maxMb: 5, types: ["pdf"] },
    { type: "tax_clearance", label: "Tax Clearance Certificate", required: true, maxMb: 5, types: ["pdf", "jpg", "png"] },
    { type: "scuml_certificate", label: "SCUML Certificate", required: false, maxMb: 5, types: ["pdf", "jpg", "png"] },
    { type: "proof_of_address", label: "Proof of Business Address", required: true, maxMb: 5, types: ["pdf", "jpg", "png"] },
    { type: "form_cac2_cac7", label: "Form CAC 2 / CAC 7", required: true, maxMb: 5, types: ["pdf"] },
  ];
  return docDefs.map((dd) => ({
    id: `doc-${dd.type}`,
    document_type: dd.type as KYCDocument["document_type"],
    file_name: uploaded ? `${dd.type}.pdf` : "",
    file_size: uploaded ? 1024000 : 0,
    mime_type: uploaded ? "application/pdf" : "",
    status: (statuses?.[dd.type] ?? (uploaded ? "uploaded" : "not_uploaded")) as KYCDocument["status"],
    required: dd.required,
    max_size_mb: dd.maxMb,
    allowed_types: dd.types,
    uploaded_at: uploaded ? d("2026-01-10T10:00:00Z") : null,
    rejection_comment: null,
  }));
}

// ── Mock Applications ──────────────────────────────────────

export const mockApplications: Application[] = [
  {
    id: "app-001",
    status: "approved",
    registration_path: "self_registration",
    current_step: 5,
    steps_completed: { company_info: true, documents: true, directors: true, account_config: true, review: true },
    company_info: {
      company_name: "Dangote Industries Ltd",
      rc_number: "RC12345",
      tin: "1234567890",
      date_of_incorporation: "1981-05-04",
      industry: "manufacturing",
      business_type: "public_limited",
      registered_address: "1 Alfred Rewane Road, Ikoyi",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
      phone_number: "+2341234567890",
      email: "info@dangote.com",
      website: "https://dangote.com",
    },
    documents: makeDocList(true, {
      cac_certificate: "verified",
      memart: "verified",
      board_resolution: "verified",
      tax_clearance: "verified",
      proof_of_address: "verified",
      form_cac2_cac7: "verified",
    }),
    directors: dangoteDirectors,
    account_config: {
      account_type: "current",
      primary_currency: "NGN",
      additional_currencies: ["USD"],
      daily_transaction_limit: 5000000000,
      per_transaction_limit: 1000000000,
      required_signatories: 2,
      signing_rule: "any_two",
      approval_threshold: 500000000,
      sms_alert_phone: "+2348001111111",
      email_alert_address: "treasury@dangote.com",
    },
    risk_score: {
      total_score: 20,
      classification: "medium",
      breakdown: [
        { criteria: "Industry is high-risk", score: 0, triggered: false },
        { criteria: "Daily transaction limit > ₦1B", score: 15, triggered: true },
        { criteria: "International transactions (Domiciliary)", score: 0, triggered: false },
        { criteria: "Number of directors > 5", score: 0, triggered: false },
        { criteria: "Company age < 2 years", score: 0, triggered: false },
      ],
    },
    feedback: [],
    timeline: [
      { id: "tl-1", event_type: "created", description: "Application created", created_at: d("2025-11-01T09:00:00Z") },
      { id: "tl-2", event_type: "submitted", description: "Application submitted for review", created_at: d("2025-11-10T14:00:00Z") },
      { id: "tl-3", event_type: "approved", description: "Application approved", created_at: d("2025-11-15T10:00:00Z") },
    ],
    created_at: d("2025-11-01T09:00:00Z"),
    updated_at: d("2025-11-15T10:00:00Z"),
    submitted_at: d("2025-11-10T14:00:00Z"),
  },
  {
    id: "app-002",
    status: "under_review",
    registration_path: "self_registration",
    current_step: 5,
    steps_completed: { company_info: true, documents: true, directors: true, account_config: true, review: true },
    company_info: {
      company_name: "TechNova Solutions",
      rc_number: "RC67890",
      tin: "9876543210",
      date_of_incorporation: "2020-03-15",
      industry: "technology",
      business_type: "limited_liability",
      registered_address: "12 Admiralty Way, Lekki Phase 1",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
      phone_number: "+2349087654321",
      email: "info@technova.ng",
      website: "https://technova.ng",
    },
    documents: makeDocList(true),
    directors: techNovaDirectors,
    account_config: {
      account_type: "current",
      primary_currency: "NGN",
      additional_currencies: [],
      daily_transaction_limit: 100000000,
      per_transaction_limit: 50000000,
      required_signatories: 1,
      signing_rule: "any_one",
    },
    risk_score: {
      total_score: 10,
      classification: "low",
      breakdown: [
        { criteria: "Industry is high-risk", score: 0, triggered: false },
        { criteria: "Daily transaction limit > ₦1B", score: 0, triggered: false },
        { criteria: "International transactions (Domiciliary)", score: 0, triggered: false },
        { criteria: "Number of directors > 5", score: 0, triggered: false },
        { criteria: "Company age < 2 years", score: 10, triggered: true },
      ],
    },
    feedback: [],
    timeline: [
      { id: "tl-4", event_type: "created", description: "Application created", created_at: d("2025-12-05T09:00:00Z") },
      { id: "tl-5", event_type: "submitted", description: "Application submitted for review", created_at: d("2025-12-15T16:00:00Z") },
      { id: "tl-6", event_type: "under_review", description: "Application is under RM review", created_at: d("2025-12-16T09:00:00Z") },
    ],
    created_at: d("2025-12-05T09:00:00Z"),
    updated_at: d("2025-12-16T09:00:00Z"),
    submitted_at: d("2025-12-15T16:00:00Z"),
  },
  {
    id: "app-003",
    status: "submitted",
    registration_path: "self_registration",
    current_step: 5,
    steps_completed: { company_info: true, documents: true, directors: true, account_config: true, review: true },
    company_info: {
      company_name: "PetroChem Nigeria",
      rc_number: "RC11223",
      tin: "1122334455",
      date_of_incorporation: "2015-07-22",
      industry: "oil_and_gas",
      business_type: "limited_liability",
      registered_address: "22 Adeola Odeku, Victoria Island",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
      phone_number: "+2348055551234",
      email: "info@petrochem.ng",
    },
    documents: makeDocList(true),
    directors: petroChemDirectors,
    account_config: {
      account_type: "domiciliary",
      primary_currency: "USD",
      additional_currencies: ["NGN", "GBP"],
      daily_transaction_limit: 2000000000,
      per_transaction_limit: 500000000,
      required_signatories: 1,
      signing_rule: "any_one",
    },
    risk_score: {
      total_score: 45,
      classification: "high",
      breakdown: [
        { criteria: "Industry is high-risk", score: 20, triggered: true },
        { criteria: "Daily transaction limit > ₦1B", score: 15, triggered: true },
        { criteria: "International transactions (Domiciliary)", score: 10, triggered: true },
        { criteria: "Number of directors > 5", score: 0, triggered: false },
        { criteria: "Company age < 2 years", score: 0, triggered: false },
      ],
    },
    feedback: [],
    timeline: [
      { id: "tl-7", event_type: "created", description: "Application created", created_at: d("2026-01-05T09:00:00Z") },
      { id: "tl-8", event_type: "submitted", description: "Application submitted for review", created_at: d("2026-01-15T11:00:00Z") },
    ],
    created_at: d("2026-01-05T09:00:00Z"),
    updated_at: d("2026-01-15T11:00:00Z"),
    submitted_at: d("2026-01-15T11:00:00Z"),
  },
  {
    id: "app-004",
    status: "draft",
    registration_path: "self_registration",
    current_step: 1,
    steps_completed: { company_info: false, documents: false, directors: false, account_config: false, review: false },
    company_info: null,
    documents: makeDocList(false),
    directors: [],
    account_config: null,
    risk_score: null,
    feedback: [],
    timeline: [
      { id: "tl-9", event_type: "created", description: "Application created", created_at: d("2026-03-20T09:00:00Z") },
    ],
    created_at: d("2026-03-20T09:00:00Z"),
    updated_at: d("2026-03-20T09:00:00Z"),
    submitted_at: null,
  },
  {
    id: "app-005",
    status: "returned_for_correction",
    registration_path: "self_registration",
    current_step: 5,
    steps_completed: { company_info: true, documents: true, directors: true, account_config: true, review: true },
    company_info: {
      company_name: "Lagos Digital Hub",
      rc_number: "RC55667",
      tin: "5566778899",
      date_of_incorporation: "2022-01-10",
      industry: "technology",
      business_type: "limited_liability",
      registered_address: "5 Yaba Tech Road, Yaba",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
      phone_number: "+2348099887766",
      email: "hello@lagosdigitalhub.ng",
      website: "https://lagosdigitalhub.ng",
    },
    documents: makeDocList(true, { board_resolution: "rejected" }),
    directors: [
      {
        id: "dir-l1",
        full_name: "Tunde Bakare",
        role: "director_and_signatory",
        date_of_birth: "1990-06-12",
        nationality: "Nigeria",
        bvn: "55566677788",
        phone_number: "+2348055566677",
        email: "tunde@lagosdigitalhub.ng",
        residential_address: "15 Herbert Macaulay, Yaba, Lagos",
        id_type: "drivers_license",
        id_number: "DL-LAG-99887",
        id_expiry_date: "2028-03-31",
        verification_status: "verified",
        verification_sent_at: d("2026-02-10T10:00:00Z"),
        verification_completed_at: d("2026-02-10T14:00:00Z"),
        id_document_uploaded: true,
        passport_photo_uploaded: true,
        signature_uploaded: true,
        created_at: d("2026-02-01T09:00:00Z"),
      },
    ],
    account_config: {
      account_type: "current",
      primary_currency: "NGN",
      additional_currencies: [],
      daily_transaction_limit: 50000000,
      per_transaction_limit: 10000000,
      required_signatories: 1,
      signing_rule: "any_one",
    },
    risk_score: {
      total_score: 10,
      classification: "low",
      breakdown: [
        { criteria: "Industry is high-risk", score: 0, triggered: false },
        { criteria: "Daily transaction limit > ₦1B", score: 0, triggered: false },
        { criteria: "International transactions (Domiciliary)", score: 0, triggered: false },
        { criteria: "Number of directors > 5", score: 0, triggered: false },
        { criteria: "Company age < 2 years", score: 10, triggered: true },
      ],
    },
    feedback: [
      {
        id: "fb-1",
        target_type: "document",
        target_id: "board_resolution",
        target_label: "Board Resolution",
        comment: "Board Resolution is illegible — please re-upload a clearer copy",
        severity: "required_fix",
        resolved: false,
        created_at: d("2026-02-20T14:00:00Z"),
        created_by: "RM Adeyemi",
      },
      {
        id: "fb-2",
        target_type: "field",
        target_id: "registered_address",
        target_label: "Registered Address",
        comment: "Company address does not match proof of address document",
        severity: "required_fix",
        resolved: false,
        created_at: d("2026-02-20T14:05:00Z"),
        created_by: "RM Adeyemi",
      },
    ],
    timeline: [
      { id: "tl-10", event_type: "created", description: "Application created", created_at: d("2026-02-01T09:00:00Z") },
      { id: "tl-11", event_type: "submitted", description: "Application submitted for review", created_at: d("2026-02-15T16:00:00Z") },
      { id: "tl-12", event_type: "returned_for_correction", description: "Application returned with 2 items to fix", created_at: d("2026-02-20T14:00:00Z") },
    ],
    created_at: d("2026-02-01T09:00:00Z"),
    updated_at: d("2026-02-20T14:00:00Z"),
    submitted_at: d("2026-02-15T16:00:00Z"),
  },
];

// ── Derived summaries ──────────────────────────────────────

export function getApplicationSummaries(): ApplicationSummary[] {
  return mockApplications.map((app) => ({
    id: app.id,
    company_name: app.company_info?.company_name ?? "Untitled Application",
    status: app.status,
    risk_classification: app.risk_score?.classification ?? null,
    current_step: app.current_step,
    steps_completed: app.steps_completed,
    director_verification_summary: {
      total: app.directors.length,
      verified: app.directors.filter((d) => d.verification_status === "verified").length,
      pending: app.directors.filter((d) => ["not_sent", "email_sent", "link_opened"].includes(d.verification_status)).length,
      failed: app.directors.filter((d) => ["failed", "expired"].includes(d.verification_status)).length,
    },
    feedback_count: app.feedback.filter((f) => !f.resolved).length,
    created_at: app.created_at,
    updated_at: app.updated_at,
    submitted_at: app.submitted_at,
  }));
}

export function getDashboardSummary(): DashboardSummary {
  const summaries = getApplicationSummaries();
  const allTimeline = mockApplications.flatMap((a) => a.timeline);
  allTimeline.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

  return {
    total_applications: summaries.length,
    by_status: {
      draft: summaries.filter((s) => s.status === "draft").length,
      submitted: summaries.filter((s) => s.status === "submitted").length,
      under_review: summaries.filter((s) => s.status === "under_review").length,
      approved: summaries.filter((s) => s.status === "approved").length,
      rejected: summaries.filter((s) => s.status === "rejected").length,
      returned_for_correction: summaries.filter((s) => s.status === "returned_for_correction").length,
    },
    recent_activity: allTimeline.slice(0, 10),
  };
}

export function getApplicationById(id: string): Application | undefined {
  return mockApplications.find((a) => a.id === id);
}
