import { PERMISSIONS } from "./permissions";
import { ROLES } from "./roles";

export const ROLE_PERMISSIONS = {
  [ROLES.PLATFORM_OWNER]: [
    PERMISSIONS.FREEZE_CUSTOMER,
    PERMISSIONS.UNFREEZE_CUSTOMER,
  ],

  [ROLES.PLATFORM_ADMIN]: [
    PERMISSIONS.FREEZE_CUSTOMER,
    PERMISSIONS.UNFREEZE_CUSTOMER,
  ],

  [ROLES.PLATFORM_COMPLIANCE]: [
    PERMISSIONS.FREEZE_CUSTOMER,
    PERMISSIONS.UNFREEZE_CUSTOMER,
  ],
};
