export const ROLES = {
  PLATFORM_OWNER: "PLATFORM_OWNER",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  PLATFORM_SUPPORT: "PLATFORM_SUPPORT",
  PLATFORM_COMPLIANCE: "PLATFORM_COMPLIANCE",
  PLATFORM_AUDITOR: "PLATFORM_AUDITOR",
} as const;
